/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentSystem;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTable.PrintMode;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


 // Define the StaffDashboard class that inherits JFrame to create a GUI window
public class StaffDashboard extends javax.swing.JFrame {
    Connection adminConnect;// Connection for admin database
    PreparedStatement pst = null;// PreparedStatement for executing SQL queries
    Statement st = null;// Statement for executing SQL queries
    ResultSet rs = null;// ResultSet for storing the result of SQL queries
    
    // Constructor for StaffDashboard
    public StaffDashboard() {
        initComponents();
        adminConnect = UserLogins.admin();// Establish connection for admin database
        Subject();// Call the Subject method
        Date();// Call the Date method
        Time();// Call the Time method
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        selectionPanel = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        subjects = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        homePage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_time = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        subjectPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();
        printPreview = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(163, 67, 67));

        formTitle.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        formTitle.setForeground(new java.awt.Color(255, 255, 255));
        formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle.setText("Student Enrollment System");
        formTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("jLabel2");
        try{
            adminConnect = UserLogins.admin();
            String username = "SELECT TOP 1 fname+ ' '+lname AS 'Username' FROM EMPLOYEE ORDER BY loginDate DESC, loginTime DESC";
            pst = adminConnect.prepareStatement(username);
            ResultSet rs = pst.executeQuery();

            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"error");
            }else{
                user.setText(rs.getString("Username"));
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentSystem/logout.png"))); // NOI18N
        logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutMouseMoved(evt);
            }
        });
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        selectionPanel.setBackground(new java.awt.Color(51, 51, 51));

        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homeMouseMoved(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });

        subjects.setForeground(new java.awt.Color(255, 255, 255));
        subjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subjects.setText("Subjects");
        subjects.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                subjectsMouseMoved(evt);
            }
        });
        subjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subjectsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout selectionPanelLayout = new javax.swing.GroupLayout(selectionPanel);
        selectionPanel.setLayout(selectionPanelLayout);
        selectionPanelLayout.setHorizontalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subjects, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        selectionPanelLayout.setVerticalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjects, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        getContentPane().add(selectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 560));

        tabs.setBackground(new java.awt.Color(242, 139, 185));

        homePage.setBackground(new java.awt.Color(246, 245, 242));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BULSU Student Enrollment System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentSystem/bsuLogo (1).png"))); // NOI18N

        l_time.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        l_date.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(l_time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        tabs.addTab("tab1", homePage);

        subjectPage.setBackground(new java.awt.Color(246, 245, 242));
        subjectPage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subjects", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(subjectTable);

        printPreview.setText("PRINT PREVIEW");
        printPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPreviewActionPerformed(evt);
            }
        });

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subjectPageLayout = new javax.swing.GroupLayout(subjectPage);
        subjectPage.setLayout(subjectPageLayout);
        subjectPageLayout.setHorizontalGroup(
            subjectPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subjectPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        subjectPageLayout.setVerticalGroup(
            subjectPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subjectPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printPreview)
                    .addComponent(print))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        tabs.addTab("tab2", subjectPage);

        getContentPane().add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 40, 1120, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseMoved
        // TODO add your handling code here:
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseMoved

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        //Logging Out
        JOptionPane.showMessageDialog(null, "Logging out");// Display a message indicating the user is logging out
        LoginForm form = new LoginForm();// Create an instance of the LoginForm
        form.show();// Display the LoginForm window
        form.setLocationRelativeTo(null);// Center the LoginForm window on the screen
        this.dispose(); // Close the current window
    }//GEN-LAST:event_logoutMouseClicked

    private void homeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseMoved
        // TODO add your handling code here:
        home.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_homeMouseMoved

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_homeMouseClicked

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_homeMousePressed

    private void subjectsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsMouseMoved
        // TODO add your handling code here:
        subjects.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_subjectsMouseMoved

    private void subjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsMouseClicked
        // TODO add your handling code here:
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_subjectsMouseClicked

    private void subjectsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsMousePressed
        // TODO add your handling code here:
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_subjectsMousePressed

    private void printPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPreviewActionPerformed
        // TODO add your handling code here:
        EmployeeSubject mySubject = new EmployeeSubject();// Create an instance of EmployeeSubject class
        mySubject.show();// Display the EmployeeSubject window
        
    }//GEN-LAST:event_printPreviewActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        EmployeeSubject mySubject = new EmployeeSubject();// Create an instance of EmployeeSubject class
        mySubject.PrintNow();// Call the PrintNow method of the EmployeeSubject instance
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StaffDashboard staffdash = new StaffDashboard();
                staffdash.show();
                staffdash.setLocationRelativeTo(null);
                
            }
        });
    }
    //Method to show Subjects
    private void Subject(){
            // SQL query to retrieve subject information based on the most recently logged-in employee
String subjectQuery = "SELECT cs.section, cs.YrLevel, cs.Semester, s.subjCode, s.subjTitle, s.lec, s.lab, SUM(s.lec + s.lab) AS \"Credit\", e.empNo, e.fName+' '+e.lname AS 'Employee Name' FROM COURSESUBJECT CS INNER JOIN SUBJECT S ON cs.subjCode = s.subjCode INNER JOIN EMPLOYEE E ON s.empNo = E.empNo WHERE e.empNo = (SELECT TOP 1 empno FROM EMPLOYEE ORDER BY loginDate DESC, loginTime DESC) GROUP BY cs.section, cs.YrLevel, cs.Semester, s.subjCode, s.subjTitle, s.lec, s.lab, e.loginDate, e.loginTime, e.empNo, e.fName, e.lName ORDER BY e.loginDate DESC, e.loginTime DESC";

        try{
            // Create a statement for executing SQL queries
            st = adminConnect.createStatement();
            // Execute the query and retrieve the result set
            rs = st.executeQuery(subjectQuery);
           // Set the result set as the model for the subjectTable
           subjectTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            // Display any exceptions that occur
            JOptionPane.showMessageDialog(null,e);
        }
    }
    // Method to set the current date
        private void Date(){
        // Create a Date object to get the current date
        Date d = new Date();
        // Define the date format
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMMM dd, yyyy");
        // Format the date
        String date = simpleDateFormat.format(d);
            // Set the formatted date to the label
        l_date.setText(date);
    }
    // Variables for handling time
    Timer t;// Timer object for updating time
    SimpleDateFormat simpleTimeFormat;// SimpleDateFormat object for formatting time
    // Method to set the current time
    private void Time(){
            // Initialize the Timer object
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 // Create a Date object to get the current time
                Date dt = new Date();
                // Define the time format
                simpleTimeFormat = new SimpleDateFormat("h:mm a");
                // Format the time
                String time = simpleTimeFormat.format(dt);
                l_time.setText(time); // Set the formatted time to the label
            }
        });
        t.start();// Start the timer
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formTitle;
    public javax.swing.JLabel home;
    public javax.swing.JPanel homePage;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel l_date;
    public javax.swing.JLabel l_time;
    public javax.swing.JLabel logout;
    public javax.swing.JButton print;
    public javax.swing.JButton printPreview;
    public javax.swing.JPanel selectionPanel;
    public javax.swing.JPanel subjectPage;
    public javax.swing.JTable subjectTable;
    public javax.swing.JLabel subjects;
    public javax.swing.JTabbedPane tabs;
    public javax.swing.JPanel titlePanel;
    public javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
