/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

// Define the StudentEnrollment class that inherits JFrame to create a GUI window
public class StudentEnrollment extends javax.swing.JFrame {
    Connection studConnect = null; // Connection for student database
    PreparedStatement pst = null;// PreparedStatement for executing SQL queries
    ResultSet rs = null;// ResultSet for storing the result of SQL queries
    

    // Constructor for StudentEnrollment
    public StudentEnrollment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studEnrollment = new javax.swing.JPanel();
        enrollmentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        lname_label = new javax.swing.JLabel();
        fname_label = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        mname_label = new javax.swing.JLabel();
        txt_mname = new javax.swing.JTextField();
        gender_label = new javax.swing.JLabel();
        bday_label = new javax.swing.JLabel();
        combo_gender = new javax.swing.JComboBox<>();
        txt_bdate = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        street_label = new javax.swing.JLabel();
        txt_street = new javax.swing.JTextField();
        brgy_label = new javax.swing.JLabel();
        txt_brgy = new javax.swing.JTextField();
        city_label = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        province_label = new javax.swing.JLabel();
        txt_province = new javax.swing.JTextField();
        postalcode_label = new javax.swing.JLabel();
        txt_postalcode = new javax.swing.JTextField();
        enrollButton = new javax.swing.JButton();
        password_label = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        studno_label = new javax.swing.JLabel();
        txt_studno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studEnrollment.setBackground(new java.awt.Color(246, 245, 242));

        enrollmentPanel.setBackground(new java.awt.Color(163, 67, 67));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDENT ENROLLMENT SYSTEM");

        javax.swing.GroupLayout enrollmentPanelLayout = new javax.swing.GroupLayout(enrollmentPanel);
        enrollmentPanel.setLayout(enrollmentPanelLayout);
        enrollmentPanelLayout.setHorizontalGroup(
            enrollmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        enrollmentPanelLayout.setVerticalGroup(
            enrollmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });

        lname_label.setText("Last Name");

        fname_label.setText("First Name");

        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });

        mname_label.setText("Middle Name");

        txt_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mnameActionPerformed(evt);
            }
        });

        gender_label.setText("Gender");

        bday_label.setText("Birth Date");

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        txt_bdate.setText("MM-DD-YYYY");
        txt_bdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_bdateMouseClicked(evt);
            }
        });
        txt_bdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bdateActionPerformed(evt);
            }
        });

        email_label.setText("Email");

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        street_label.setText("Street");

        txt_street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_streetActionPerformed(evt);
            }
        });

        brgy_label.setText("Baranggay");

        txt_brgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brgyActionPerformed(evt);
            }
        });

        city_label.setText("City");

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        province_label.setText("Province");

        txt_province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_provinceActionPerformed(evt);
            }
        });

        postalcode_label.setText("Postal Code");

        txt_postalcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_postalcodeActionPerformed(evt);
            }
        });

        enrollButton.setText("Enroll");
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });

        password_label.setText("Password");

        studno_label.setText("Student No.");

        txt_studno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studEnrollmentLayout = new javax.swing.GroupLayout(studEnrollment);
        studEnrollment.setLayout(studEnrollmentLayout);
        studEnrollmentLayout.setHorizontalGroup(
            studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enrollmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(studEnrollmentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studEnrollmentLayout.createSequentialGroup()
                        .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studEnrollmentLayout.createSequentialGroup()
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(studno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_studno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(lname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(fname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(mname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(gender_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(bday_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studEnrollmentLayout.createSequentialGroup()
                                .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(163, 163, 163)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(city_label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(brgy_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(street_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(province_label, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addComponent(postalcode_label, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_street, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_brgy, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_province, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        studEnrollmentLayout.setVerticalGroup(
            studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studEnrollmentLayout.createSequentialGroup()
                .addComponent(enrollmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_studno)
                    .addComponent(txt_street)
                    .addComponent(street_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_brgy)
                    .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_lname)
                        .addComponent(brgy_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studEnrollmentLayout.createSequentialGroup()
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fname_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mname_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_mname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender_label)
                            .addComponent(combo_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bday_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_bdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enrollButton))))
                    .addGroup(studEnrollmentLayout.createSequentialGroup()
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(city_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_city))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(province_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_province))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postalcode_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_postalcode))
                        .addGap(74, 74, 74)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studEnrollmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_pass)
                    .addComponent(password_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(studEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnameActionPerformed

    private void txt_bdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bdateActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_streetActionPerformed

    private void txt_brgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brgyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brgyActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_provinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_provinceActionPerformed

    private void txt_postalcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_postalcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_postalcodeActionPerformed

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        // Retrieve input values from form fields
        String studno = txt_studno.getText();
        String lname = txt_lname.getText();
        String fname = txt_fname.getText();
        String mname = txt_mname.getText();
        String gender = (String) combo_gender.getSelectedItem();
        String bdate = txt_bdate.getText();
        String email = txt_email.getText();
        String pass = txt_pass.getText();
        String street = txt_street.getText();
        String brgy = txt_brgy.getText();
        String city = txt_city.getText();
        String province = txt_province.getText();
        String postal = txt_postalcode.getText();
        String stat = "Active"; // Set status as Active
        String logindate = "";
        String logintime = "";
        // Create an instance of StudentEnrollment
        StudentEnrollment enroll = new StudentEnrollment();
        
        // Get the current date
        Date userDate = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        String date = df.format(userDate);
        // Check if any required field is empty
        if (lname.isEmpty()||fname.isEmpty()||mname.isEmpty()||gender.isEmpty()||bdate.isEmpty()||email.isEmpty()||street.isEmpty()||
            brgy.isEmpty()||city.isEmpty()||province.isEmpty()||postal.isEmpty()||pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill the required field.");
            return; // Exit the method without proceeding further
        }
        // Construct an SQL INSERT query to add a new student record to the STUDENT table
        String insertQuery = "INSERT INTO STUDENT values ('"+studno+"','"+lname+"','"+fname+"','"+mname+"','"+gender+"','"+bdate+"','"+street+"',"
                + "'"+brgy+"','"+city+"','"+province+"','"+postal+"','"+date+"','"+email+"','"+pass+"','"+stat+"','"+logindate+"','"+logintime+"')";
        // Prepare SQL query to check if the email already exists
        String selectQuery = "SELECT email from STUDENT";
        // Prepare SQL query to insert log
        String insertLog = "INSERT INTO STUDENT_LOG VALUES('"+studno+"','Successfully enrolled',default)";
        
        try{
             // Establish connection for student database
            // Check if the email already exists in the database
            studConnect = UserLogins.stud();
            pst = studConnect.prepareStatement(selectQuery);
            rs = pst.executeQuery();
            
                //Checks if the ResultSet has any row
                if(rs.next()){
                    //If the email already exists, show a message and exit 
                    if(rs.getString("email").equals(email)){
                       JOptionPane.showMessageDialog(null,"User with this email already exist");
                       
                    return;
                    }
                }
 // If the email is valid (ends with "@bulsu.edu.ph"), proceed with insertion
            if(email.endsWith("@bulsu.edu.ph")){
                 // Check password constraints
                if (pass.length() != 8 || !pass.matches("^[a-zA-Z]*[0-9]{2}[a-zA-Z0-9]*$")) {
            JOptionPane.showMessageDialog(null, "Password should be limited to 8 characters, consist of only letters and digits, and contain at least two digits.");
            }else{
                // Insert the new record
                pst = studConnect.prepareStatement(insertQuery);
                pst.execute();
                JOptionPane.showMessageDialog(null,"You are officially enrolled");
                // Insert the log record
                PreparedStatement insertlogPST = studConnect.prepareStatement(insertLog);
                insertlogPST.execute();
                // Open the LoginForm
                LoginForm login = new LoginForm();
                login.show();
                login.setLocationRelativeTo(null);
                this.dispose(); // Close the current window
                }
                
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Input");
            }
            
            
        }catch(Exception e){
             // Display any exception that occurs
            JOptionPane.showMessageDialog(null,e);
        }
        
        

    }//GEN-LAST:event_enrollButtonActionPerformed

    private void txt_studnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studnoActionPerformed

    private void txt_bdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_bdateMouseClicked
        // TODO add your handling code here:
        txt_bdate.setText(""); //removes the text "MM-DD-YYYY" which acts as a pattern
    }//GEN-LAST:event_txt_bdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEnrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEnrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bday_label;
    public javax.swing.JLabel brgy_label;
    public javax.swing.JLabel city_label;
    public javax.swing.JComboBox<String> combo_gender;
    public javax.swing.JLabel email_label;
    public javax.swing.JButton enrollButton;
    public javax.swing.JPanel enrollmentPanel;
    public javax.swing.JLabel fname_label;
    public javax.swing.JLabel gender_label;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lname_label;
    public javax.swing.JLabel mname_label;
    public javax.swing.JLabel password_label;
    public javax.swing.JLabel postalcode_label;
    public javax.swing.JLabel province_label;
    public javax.swing.JLabel street_label;
    public javax.swing.JPanel studEnrollment;
    public javax.swing.JLabel studno_label;
    public javax.swing.JTextField txt_bdate;
    public javax.swing.JTextField txt_brgy;
    public javax.swing.JTextField txt_city;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_fname;
    public javax.swing.JTextField txt_lname;
    public javax.swing.JTextField txt_mname;
    public javax.swing.JPasswordField txt_pass;
    public javax.swing.JTextField txt_postalcode;
    public javax.swing.JTextField txt_province;
    public javax.swing.JTextField txt_street;
    public javax.swing.JTextField txt_studno;
    // End of variables declaration//GEN-END:variables

}
