/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentSystem;

import static enrollmentSystem.EmployeeSubject.employeeSubject;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.SQLException;
import javax.swing.Timer;

 // Define the StudDashboard class that inherits JFrame to create a GUI window
public class StudDashboard extends javax.swing.JFrame {
    Connection studConnect;// Connection for student database
    Connection adminConnect;// Connection for admin database
    PreparedStatement pst = null;// PreparedStatement for executing SQL queries
    Statement st = null;// Statement for executing SQL queries
    ResultSet rs = null;// ResultSet for storing the result of SQL queries
   
    // Constructor for StudDashboard
    public StudDashboard() {
        initComponents();
        TableFormat();// Set up the format for the table
        Date();// Display or update the current date on the dashboard
        Time();// Display or update the current time on the dashboard
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studEnrollmentForm = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        formSelection = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        assessment = new javax.swing.JLabel();
        enroll = new javax.swing.JLabel();
        studEnrollmentTabs = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_time = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        assessmentTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_studno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        combo_section = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        combo_yrlvl = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        combo_semester = new javax.swing.JComboBox<>();
        enter = new javax.swing.JButton();
        printPreview = new javax.swing.JButton();
        printCor = new javax.swing.JButton();
        tablePane = new javax.swing.JScrollPane();
        enrolledSubject = new javax.swing.JTable();
        certificate = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        registrationInfo = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        studInfo1 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        studInfo2 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        studInfo3 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        studInfo4 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        subjcode = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        subjtitle = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        lecture = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        credits = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        laboratory = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        sections = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        employee = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studEnrollmentForm.setBackground(new java.awt.Color(163, 67, 67));

        formTitle.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        formTitle.setForeground(new java.awt.Color(255, 255, 255));
        formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle.setText("Student Enrollment System");
        formTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("jLabel2");
        try{
            adminConnect = UserLogins.admin();
            String username = "SELECT TOP 1 fname+ ' '+lname AS 'Username' FROM STUDENT ORDER BY loginDate DESC, loginTime DESC";
            pst = adminConnect.prepareStatement(username);
            ResultSet rs = pst.executeQuery();

            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"error");
            }else{
                user.setText(rs.getString("Username"));
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentSystem/logout.png"))); // NOI18N
        logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutMouseMoved(evt);
            }
        });
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout studEnrollmentFormLayout = new javax.swing.GroupLayout(studEnrollmentForm);
        studEnrollmentForm.setLayout(studEnrollmentFormLayout);
        studEnrollmentFormLayout.setHorizontalGroup(
            studEnrollmentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studEnrollmentFormLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout)
                .addContainerGap())
        );
        studEnrollmentFormLayout.setVerticalGroup(
            studEnrollmentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addGroup(studEnrollmentFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(studEnrollmentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout)))
        );

        getContentPane().add(studEnrollmentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        formSelection.setBackground(new java.awt.Color(51, 51, 51));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homeMouseMoved(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });

        assessment.setForeground(new java.awt.Color(255, 255, 255));
        assessment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assessment.setText("Assessment");
        assessment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                assessmentMouseMoved(evt);
            }
        });
        assessment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assessmentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                assessmentMousePressed(evt);
            }
        });

        enroll.setForeground(new java.awt.Color(255, 255, 255));
        enroll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enroll.setText("Enrollment");
        enroll.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enrollMouseMoved(evt);
            }
        });
        enroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrollMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enrollMousePressed(evt);
            }
        });

        javax.swing.GroupLayout formSelectionLayout = new javax.swing.GroupLayout(formSelection);
        formSelection.setLayout(formSelectionLayout);
        formSelectionLayout.setHorizontalGroup(
            formSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(assessment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(enroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formSelectionLayout.setVerticalGroup(
            formSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSelectionLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assessment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );

        getContentPane().add(formSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 690));

        studEnrollmentTabs.setBackground(new java.awt.Color(246, 245, 242));

        homeTab.setBackground(new java.awt.Color(246, 245, 242));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentSystem/bsuLogo (1).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BULSU Student Enrollment System");

        l_time.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        l_date.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                .addComponent(l_time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        studEnrollmentTabs.addTab("tab1", homeTab);

        assessmentTab.setBackground(new java.awt.Color(246, 245, 242));

        jPanel5.setBackground(new java.awt.Color(246, 245, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Student No:");

        txt_studno.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Section:");

        combo_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT 1A-G1", "BSIT 1A-G2", "BSIT 1B-G1", "BSIT 1B-G2", "BSIT 1C-G1", "BSIT 1C-G2", "BSIT 1D-G1", "BSIT 1D-G2", "BSIT 2A-G1", "BSIT 2A-G2", "BSIT 2B-G1", "BSIT 2B-G2", "BSIT 2C-G1", "BSIT 2C-G2", "BSIT 2D-G1", "BSIT 2D-G2", "BSIS 1A-G1", "BSIS 1A-G2", "BSIS 1B-G1", "BSIS 1B-G2", "BSIS 1C-G1", "BSIS 1C-G2", "BSIS 1D-G1", "BSIS 1D-G2", "BSIS 2A-G1", "BSIS 2A-G2", "BSIS 2B-G1", "BSIS 2B-G2", "BSIS 2C-G1", "BSIS 2C-G2", "BSIS 2D-G1", "BSIS 2D-G2", "BLIS 1A-G1", "BLIS 1A-G2", "BLIS 1B-G1", "BLIS 1B-G2", "BLIS 1C-G1", "BLIS 1C-G2", "BLIS 1D-G1", "BLIS 1D-G2", "BLIS 2A-G1", "BLIS 2A-G2", "BLIS 2B-G1", "BLIS 2B-G2", "BLIS 2C-G1", "BLIS 2C-G2", "BLIS 2D-G1", "BLIS 2D-G2" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Year Level");

        combo_yrlvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year", " " }));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Semester:");

        combo_semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Semester", "2nd Semester", " " }));

        enter.setBackground(new java.awt.Color(255, 150, 0));
        enter.setText("ENROLL");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        printPreview.setBackground(new java.awt.Color(153, 153, 153));
        printPreview.setText("PRINT PREVIEW");
        printPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPreviewActionPerformed(evt);
            }
        });

        printCor.setBackground(new java.awt.Color(102, 102, 102));
        printCor.setText("PRINT COR");
        printCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printCorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_studno, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_section, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_yrlvl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_semester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 622, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(printPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_studno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printPreview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_yrlvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        enrolledSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePane.setViewportView(enrolledSubject);

        javax.swing.GroupLayout assessmentTabLayout = new javax.swing.GroupLayout(assessmentTab);
        assessmentTab.setLayout(assessmentTabLayout);
        assessmentTabLayout.setHorizontalGroup(
            assessmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(assessmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePane))
                .addContainerGap())
        );
        assessmentTabLayout.setVerticalGroup(
            assessmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assessmentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        studEnrollmentTabs.addTab("tab2", assessmentTab);

        certificate.setBackground(new java.awt.Color(255, 255, 255));
        certificate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("BULACAN STATE UNIVERSITY");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(jTextArea2);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Guinhawa, City of Malolos, Bulacan");
        jTextArea3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setViewportView(jTextArea3);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("C E R T I F I C A T E  O F  R E G I S T R A T I O N");
        jTextArea4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setViewportView(jTextArea4);

        jScrollPane6.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane6.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(jTextArea5);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollmentSystem/bsuLogo (2).png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane7.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        registrationInfo.setColumns(20);
        registrationInfo.setRows(5);
        registrationInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane7.setViewportView(registrationInfo);

        jScrollPane8.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane8.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane8.setViewportView(jTextArea6);

        jScrollPane9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane9.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("STUDENT GENERAL INFORMATION");
        jTextArea7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane9.setViewportView(jTextArea7);

        jScrollPane10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane10.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        studInfo1.setColumns(20);
        studInfo1.setRows(5);
        studInfo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane10.setViewportView(studInfo1);

        jScrollPane11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane11.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        studInfo2.setColumns(20);
        studInfo2.setRows(5);
        studInfo2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane11.setViewportView(studInfo2);

        jScrollPane12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane12.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        studInfo3.setColumns(20);
        studInfo3.setRows(5);
        studInfo3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane12.setViewportView(studInfo3);

        jScrollPane13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane13.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        studInfo4.setColumns(20);
        studInfo4.setRows(5);
        studInfo4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane13.setViewportView(studInfo4);

        jScrollPane14.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane14.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane14.setViewportView(jTextArea8);

        jScrollPane15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane15.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("SUBJECT CODE");
        jTextArea9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane15.setViewportView(jTextArea9);

        jScrollPane16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane16.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("SUBJECT TITLE");
        jTextArea10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane16.setViewportView(jTextArea10);

        jScrollPane17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane17.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        subjcode.setColumns(20);
        subjcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subjcode.setRows(5);
        subjcode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane17.setViewportView(subjcode);

        jScrollPane18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane18.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        subjtitle.setColumns(20);
        subjtitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subjtitle.setRows(5);
        subjtitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane18.setViewportView(subjtitle);

        jScrollPane19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane19.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane19.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea11.setRows(5);
        jTextArea11.setText("LEB");
        jTextArea11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane19.setViewportView(jTextArea11);

        jScrollPane20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane20.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane20.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane20.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lecture.setColumns(20);
        lecture.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lecture.setRows(5);
        lecture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane20.setViewportView(lecture);

        jScrollPane21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane21.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane21.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane21.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea12.setRows(5);
        jTextArea12.setText("LAB");
        jTextArea12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane21.setViewportView(jTextArea12);

        jScrollPane22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane22.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane22.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane22.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        credits.setColumns(20);
        credits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        credits.setRows(5);
        credits.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane22.setViewportView(credits);

        jScrollPane23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane23.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane23.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane23.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea13.setRows(5);
        jTextArea13.setText("CREDIT");
        jTextArea13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane23.setViewportView(jTextArea13);

        jScrollPane24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane24.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane24.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane24.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        laboratory.setColumns(20);
        laboratory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        laboratory.setRows(5);
        laboratory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane24.setViewportView(laboratory);

        jScrollPane25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane25.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane25.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane25.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea14.setRows(5);
        jTextArea14.setText("SECTION");
        jTextArea14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane25.setViewportView(jTextArea14);

        jScrollPane26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane26.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane26.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane26.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        sections.setColumns(20);
        sections.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sections.setRows(5);
        sections.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane26.setViewportView(sections);

        jScrollPane27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane27.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane27.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane27.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea15.setRows(5);
        jTextArea15.setText("EMPLOYEE SIGNATURE");
        jTextArea15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane27.setViewportView(jTextArea15);

        jScrollPane28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane28.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane28.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane28.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        employee.setColumns(20);
        employee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employee.setRows(5);
        employee.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane28.setViewportView(employee);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane17)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                .addGap(155, 155, 155))
        );

        certificate.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, -1, 610));

        studEnrollmentTabs.addTab("tab3", certificate);

        getContentPane().add(studEnrollmentTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 32, 1100, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseMoved
        // TODO add your handling code here:
        home.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_homeMouseMoved

    private void assessmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentMouseMoved
        // TODO add your handling code here:
        assessment.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_assessmentMouseMoved

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        studEnrollmentTabs.setSelectedIndex(0);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        studEnrollmentTabs.setSelectedIndex(0);
    }//GEN-LAST:event_homeMouseClicked

    private void assessmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentMouseClicked
          // This method is triggered when the mouse is clicked on the assessment component
        studEnrollmentTabs.setSelectedIndex(1);
        try{
            adminConnect = UserLogins.admin();// Connect to the admin database
             // SQL query to get the most recent student record, along with their full name
            String student = "SELECT TOP 1*, fname+ ' '+lname AS 'Username' FROM STUDENT ORDER BY loginDate DESC, loginTime DESC";
            pst = adminConnect.prepareStatement(student); // Prepare the SQL statement
            ResultSet rs = pst.executeQuery(); // Execute the query and get the result set
            
            // Check if the result set is empty
            if(!rs.next()){
                // If no records are found, show a message dialog
                JOptionPane.showMessageDialog(null, "No Record Found");
            }else{
                // If a record is found, set the text of txt_studno with the student's number
                txt_studno.setText(rs.getString("studentNo"));
                
            }
        }catch(Exception e){
            // If an exception occurs, show a message dialog with the error message
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_assessmentMouseClicked

    private void assessmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assessmentMousePressed
        // TODO add your handling code here:
        studEnrollmentTabs.setSelectedIndex(1);
    }//GEN-LAST:event_assessmentMousePressed

    private void logoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseMoved
        // TODO add your handling code here:
        logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseMoved

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        //Logging Out
        JOptionPane.showMessageDialog(null, "Logging out");// Show a message dialog indicating that the user is logging out
        LoginForm form = new LoginForm();// Create a new instance of the LoginForm
        form.show();// Display the login form
        form.setLocationRelativeTo(null);// Center the login form on the screen
        this.dispose();// Dispose of the current window to close it
    }//GEN-LAST:event_logoutMouseClicked

    private void enrollMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollMouseMoved
        // TODO add your handling code here:
        enroll.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_enrollMouseMoved

    private void enrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollMouseClicked
        // TODO add your handling code here:
        studEnrollmentTabs.setSelectedIndex(2);
    }//GEN-LAST:event_enrollMouseClicked

    private void enrollMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrollMousePressed
        // TODO add your handling code here:
        studEnrollmentTabs.setSelectedIndex(2);
    }//GEN-LAST:event_enrollMousePressed

    private void printCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printCorActionPerformed
        //To Print Certificate of Registration
        PrinterJob job = PrinterJob.getPrinterJob();// Create a PrinterJob instance
        job.setJobName("Print Data");// Set the name of the print job

        // Set the Printable object for the print job
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pf, int pageNum) throws PrinterException {
                if(pageNum > 0){
                     // Check if the page number is greater than 0 (only one page to print)
                    return Printable.NO_SUCH_PAGE;// No such page to print
                }
                // Cast the Graphics object to Graphics2D for more control
                Graphics2D g2 = (Graphics2D)graphics;
                g2.translate(pf.getImageableX(), pf.getImageableY());// Translate the graphics to the imageable area of the page
                g2.scale(0.450,0.900);// Scale the graphics to fit the content to the page

                // Paint the content (certificate) onto the Graphics2D object
                certificate.paint(g2);
                return Printable.PAGE_EXISTS;// Indicate that the page exists and was rendered

            }
        });
        try{
            //To print the document
            job.print();
        }catch(PrinterException e){
            // If a PrinterException occurs, show a message dialog with the error
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_printCorActionPerformed

    private void printPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPreviewActionPerformed
        //To see Certificate of Registration Preview
        studEnrollmentTabs.setSelectedIndex(2);

    }//GEN-LAST:event_printPreviewActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // Retrieve input values from form fields
        String studno = txt_studno.getText();
        String section = (String) combo_section.getSelectedItem();
        String yrlvl = (String) combo_yrlvl.getSelectedItem();
        String semester = (String) combo_semester.getSelectedItem();
        
        // Get the current date
        Date regDate = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        String date = df.format(regDate);

        //To check if the student exist on the student table and To select the student who recently login
        String studQuery = "SELECT studentNo FROM STUDENT WHERE loginTime = (SELECT TOP 1 loginTime FROM STUDENT ORDER BY loginDate DESC, loginTime DESC)";

        //Insert to Registration table
        String regQuery = "INSERT INTO REGISTRATION VALUES ('"+studno+"','"+section+"','"+date+"')";

        //Checking if the student number already exist
        String rQuery = "SELECT studentNo FROM REGISTRATION WHERE studentNo=?";

        //To insert the log of the student's registration
        String insertLog = "INSERT INTO STUDENT_LOG VALUES('"+studno+"','Successfully registered',default)";
        // SQL query to log the student checking their Certificate of Registration (COR)
         String insertLogIfRegistered = "INSERT INTO STUDENT_LOG VALUES('"+studno+"','Checked their COR',default)";
        
        try{
            studConnect = UserLogins.stud();// Connect to the student database
            pst = studConnect.prepareStatement(studQuery);// Prepare and execute the query to check if the student recently logged in
            rs = pst.executeQuery();
            // Prepare the statement to check if the student number already exists in the REGISTRATION table
            PreparedStatement checkPst = studConnect.prepareStatement(rQuery);

            // If the student number field is empty, show an error message and exit the method
            if(studno.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill in all the required fields.");
                return; // Exit the method without proceeding further
            }
            // Set the student number in the check query and execute it
            checkPst.setString(1, studno);
            ResultSet checkRs = checkPst.executeQuery();
            // If the student number already exists, show an error message and log the action
            if(checkRs.next()){
                JOptionPane.showMessageDialog(null, "User already exist");
                PreparedStatement insertlogPST = studConnect.prepareStatement(insertLogIfRegistered);
                insertlogPST.execute();
                PrintSubject(yrlvl,semester);// Print the subject and student details
                printStudentDetails(yrlvl,semester);
                return;

            }
             // If the student exists in the STUDENT table and matches the student number, insert the registration record
            if(rs.next()){
                if(rs.getString("studentNo").equals(studno)){
                    // Insert the registration details into the REGISTRATION table
                    pst = studConnect.prepareStatement(regQuery);
                    pst.execute();
                     // Show a success message
                    JOptionPane.showMessageDialog(null,"Record added successfully");
                    // Log the student's registration
                    PreparedStatement insertlogPST = studConnect.prepareStatement(insertLog);
                    insertlogPST.execute();
                    // Clear the student number field and disable the 'enter' button
                    txt_studno.setText("");
                    enter.disable(); 
                    
                    // Print the subject and student details
                    PrintSubject(yrlvl,semester);
                    printStudentDetails(yrlvl,semester);

                }else{
                     // Show an error message if the student record is not found
                    JOptionPane.showMessageDialog(null, "Student record not found");
                }
            }else{
                
                 // Show an error message if the student record is not found
                JOptionPane.showMessageDialog(null, "Student record not found");
            }
        }catch(Exception e){
            // Show an error message if an exception occurs
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudDashboard().setVisible(true);
            }
        });
    }
    // This method formats the table display
    private void TableFormat(){
         // Get the header of the 'enrolledSubject' table
        JTableHeader header = enrolledSubject.getTableHeader();
        header.setVisible(true);// Make the header of the table visible
        tablePane.getColumnHeader().setVisible(true);// Make the column header of the enclosing scroll pane visible
        // Set the background color of the viewport (the visible part of the scroll pane) to white
        tablePane.getViewport().setBackground(Color.white);
    }
    // Method to print subjects based on year level and semester
    private void PrintSubject(String yrlvl, String semester){
// SQL query to select relevant subject information for the student
String printCOR = "SELECT cs.subjCode AS 'SUBJECT CODE', sub.subjTitle AS 'SUBJECT TITLE', sub.lec AS 'LEC', sub.lab AS 'LAB', SUM(sub.lec + sub.lab) AS \"CREDIT\", sec.section AS 'SECTION', " +
"emp.fName + ' ' + emp.lName AS 'Employee Name' " +
"FROM REGISTRATION AS reg " +
"INNER JOIN STUDENT AS stud ON reg.StudentNo = stud.StudentNo " +
"INNER JOIN SECTION AS sec ON reg.Section = sec.Section " +
"INNER JOIN COURSE AS crs ON sec.CourseCode = crs.CourseCode " +
"INNER JOIN COLLEGE AS col ON crs.colCode = col.colCode " +
"INNER JOIN COURSESUBJECT AS cs ON sec.Section = cs.Section " +
"INNER JOIN SUBJECT AS sub ON cs.subjCode = sub.subjCode " +
"INNER JOIN EMPLOYEE emp ON sub.empNo = emp.empNo " +
"WHERE reg.studentNo = (SELECT TOP 1 studentNo FROM STUDENT ORDER BY loginDate DESC, loginTime DESC) AND cs.YrLevel = '"+yrlvl+"' AND cs.semester = '"+semester+"' " +
"GROUP BY reg.registrationNo, stud.studentNo, stud.fName, stud.lName, stud.bDate, stud.gender, col.colName, crs.courseDesc, cs.yrlevel, cs.semester, cs.subjCode, sub.subjTitle, sub.lec, sub.lab, sec.section, stud.loginDate, stud.loginTime, emp.fname, emp.lname " +
"ORDER BY stud.loginDate DESC, stud.loginTime DESC";
            try{
                
            adminConnect = UserLogins.admin();// Connect to the admin database
            st = studConnect.createStatement();// Create a statement object to execute the query
            rs = st.executeQuery(printCOR); // Execute the query and get the result set
            enrolledSubject.setModel(DbUtils.resultSetToTableModel(rs));// Set the model of the enrolledSubject table to display the result set
            DefaultTableModel model = (DefaultTableModel) enrolledSubject.getModel();// Get the table model
            // Loop through each row in the table and extract the data
            for(int i = 0; i < enrolledSubject.getRowCount(); i++){
                 // Get each value from the row
                String subcode = enrolledSubject.getValueAt(i, 0).toString();
                String subtitle = enrolledSubject.getValueAt(i, 1).toString();
                String lec = enrolledSubject.getValueAt(i, 2).toString();
                String lab = enrolledSubject.getValueAt(i, 3).toString();
                String credit = enrolledSubject.getValueAt(i, 4).toString();
                String section = enrolledSubject.getValueAt(i, 5).toString();
                String emp = enrolledSubject.getValueAt(i, 6).toString();
                subjcode.setText(subjcode.getText()+subcode+"\n");
                subjtitle.setText(subjtitle.getText()+subtitle+"\n");
                lecture.setText(lecture.getText()+lec+"\n");
                laboratory.setText(laboratory.getText()+lab+"\n");
                credits.setText(credits.getText()+credit+"\n");
                sections.setText(sections.getText()+section+"\n");
                employee.setText(employee.getText()+emp+"\n");
                
            }
                    
            }catch(Exception e){
                 // Show an error message dialog if an exception occurs
                JOptionPane.showMessageDialog(null, e);
        }
    }
    // Method to print detailed student information based on year level and semester
    private void printStudentDetails(String yrlvl, String semester){
        // SQL query to select detailed information about the student and their enrollment
        String printStudentDetails = "SELECT reg.registrationNo, stud.studentNo, stud.fName+ ' '+stud.lName AS 'Student Name', stud.bdate, DATEDIFF(YEAR, stud.bDate, GETDATE()) AS Age, stud.gender, col.colName, crs.courseDesc, cs.yrlevel, cs.semester, cs.subjCode, sub.subjTitle, sub.lec, sub.lab, SUM(sub.lec + sub.lab) AS Credit, sec.section, stud.dateEnrolled, reg.registereddate, emp.fName+ ' '+emp.lName AS 'Employee Name' " +
        "FROM REGISTRATION AS reg " +
        "INNER JOIN STUDENT AS stud ON reg.StudentNo = stud.StudentNo " +
        "INNER JOIN SECTION AS sec ON reg.Section = sec.Section " +
        "INNER JOIN COURSE AS crs ON sec.CourseCode = crs.CourseCode " +
        "INNER JOIN COLLEGE AS col ON crs.colCode = col.colCode " +
        "INNER JOIN COURSESUBJECT AS cs ON sec.Section = cs.Section " +
        "INNER JOIN SUBJECT AS sub ON cs.subjCode = sub.subjCode " +
        "INNER JOIN EMPLOYEE AS emp ON sub.empNo = emp.empNo " +
        "WHERE reg.studentNo = (SELECT TOP 1 studentNo FROM STUDENT ORDER BY loginDate DESC, loginTime DESC) AND cs.YrLevel = '"+yrlvl+"' AND cs.semester = '"+semester+"' " +
        "GROUP BY reg.registrationNo, stud.studentNo, stud.fName, stud.lName, stud.bDate, stud.gender, col.colName, crs.courseDesc, cs.yrlevel, cs.semester, cs.subjCode, sub.subjTitle, sub.lec, sub.lab, sec.section, stud.dateEnrolled, reg.registereddate, stud.loginDate, stud.loginTime, emp.fname, emp.lname " +
        "ORDER BY stud.loginDate DESC, stud.loginTime DESC";
        try{
            adminConnect = UserLogins.admin(); // Connect to the admin database
            pst = studConnect.prepareStatement(printStudentDetails);// Prepare and execute the query to retrieve student details
            rs = pst.executeQuery();
             // Check if there is any result
            if(!rs.next()){ 
                 // If no record is found, show an error message
                JOptionPane.showMessageDialog(null, "Record not Found");
            }else{
                // If a record is found, extract and display the details
                String regno = rs.getString("registrationNo");
                String college = rs.getString("colName");
                String course = rs.getString("courseDesc");
                registrationInfo.setText(registrationInfo.getText()+"Registration No: "+regno+"\n");
                registrationInfo.setText(registrationInfo.getText()+"College: "+college+"\n");
                registrationInfo.setText(registrationInfo.getText()+"Course: "+course+"\n");
                String studno = rs.getString("studentNo");
                String studname = rs.getString("Student Name");
                studInfo1.setText(studInfo1.getText()+"Student No: "+studno+"\n");
                studInfo1.setText(studInfo1.getText()+"Student Name: "+studname+"\n");
                String studgender = rs.getString("gender");
                String studage = rs.getString("age");
                studInfo2.setText(studInfo2.getText()+"Gender: "+studgender+"\n");
                studInfo2.setText(studInfo2.getText()+"Age: "+studage+"\n");
                String studyrlvl = rs.getString("yrlevel");
                String studsem = rs.getString("semester");
                studInfo3.setText(studInfo3.getText()+"Year Level: "+studyrlvl+"\n");
                studInfo3.setText(studInfo3.getText()+"Semester: "+studsem+"\n");
                String dateEnrolled = rs.getString("dateEnrolled");
                String regDate = rs.getString("registereddate");
                studInfo4.setText(studInfo4.getText()+"Date Enrolled: "+dateEnrolled+"\n");
                studInfo4.setText(studInfo4.getText()+"Date Registered: "+regDate+"\n");
                
            }
        }catch(Exception e){
            // Show an error message dialog if an exception occurs
            JOptionPane.showMessageDialog(null,e);
        }
    }
    // Method to set the current date
        private void Date(){
        // Create a Date object to get the current date
        Date d = new Date();
        // Define the date format
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMMM dd, yyyy");
        // Format the date
        String date = simpleDateFormat.format(d);
            // Set the formatted date to the label
        l_date.setText(date);
    }
    // Variables for handling time
    Timer t;// Timer object for updating time
    SimpleDateFormat simpleTimeFormat;// SimpleDateFormat object for formatting time
    // Method to set the current time
    private void Time(){
            // Initialize the Timer object
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 // Create a Date object to get the current time
                Date dt = new Date();
                // Define the time format
                simpleTimeFormat = new SimpleDateFormat("h:mm a");
                // Format the time
                String time = simpleTimeFormat.format(dt);
                l_time.setText(time); // Set the formatted time to the label
            }
        });
        t.start();// Start the timer
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel assessment;
    public javax.swing.JPanel assessmentTab;
    public javax.swing.JPanel certificate;
    public javax.swing.JComboBox<String> combo_section;
    public javax.swing.JComboBox<String> combo_semester;
    public javax.swing.JComboBox<String> combo_yrlvl;
    public javax.swing.JTextArea credits;
    public javax.swing.JTextArea employee;
    public javax.swing.JLabel enroll;
    public javax.swing.JTable enrolledSubject;
    public javax.swing.JButton enter;
    public javax.swing.JPanel formSelection;
    public javax.swing.JLabel formTitle;
    public javax.swing.JLabel home;
    public javax.swing.JPanel homeTab;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    public javax.swing.JScrollPane jScrollPane16;
    public javax.swing.JScrollPane jScrollPane17;
    public javax.swing.JScrollPane jScrollPane18;
    public javax.swing.JScrollPane jScrollPane19;
    public javax.swing.JScrollPane jScrollPane20;
    public javax.swing.JScrollPane jScrollPane21;
    public javax.swing.JScrollPane jScrollPane22;
    public javax.swing.JScrollPane jScrollPane23;
    public javax.swing.JScrollPane jScrollPane24;
    public javax.swing.JScrollPane jScrollPane25;
    public javax.swing.JScrollPane jScrollPane26;
    public javax.swing.JScrollPane jScrollPane27;
    public javax.swing.JScrollPane jScrollPane28;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTextArea jTextArea10;
    public javax.swing.JTextArea jTextArea11;
    public javax.swing.JTextArea jTextArea12;
    public javax.swing.JTextArea jTextArea13;
    public javax.swing.JTextArea jTextArea14;
    public javax.swing.JTextArea jTextArea15;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea jTextArea3;
    public javax.swing.JTextArea jTextArea4;
    public javax.swing.JTextArea jTextArea5;
    public javax.swing.JTextArea jTextArea6;
    public javax.swing.JTextArea jTextArea7;
    public javax.swing.JTextArea jTextArea8;
    public javax.swing.JTextArea jTextArea9;
    public javax.swing.JLabel l_date;
    public javax.swing.JLabel l_time;
    public javax.swing.JTextArea laboratory;
    public javax.swing.JTextArea lecture;
    public javax.swing.JLabel logout;
    public javax.swing.JButton printCor;
    public javax.swing.JButton printPreview;
    public javax.swing.JTextArea registrationInfo;
    public javax.swing.JTextArea sections;
    public javax.swing.JPanel studEnrollmentForm;
    public javax.swing.JTabbedPane studEnrollmentTabs;
    public javax.swing.JTextArea studInfo1;
    public javax.swing.JTextArea studInfo2;
    public javax.swing.JTextArea studInfo3;
    public javax.swing.JTextArea studInfo4;
    public javax.swing.JTextArea subjcode;
    public javax.swing.JTextArea subjtitle;
    public javax.swing.JScrollPane tablePane;
    public javax.swing.JTextField txt_studno;
    public javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
